fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader: true
    view:
        view_response_listener:  true
    exception:
        codes: ~
        messages: ~
    format_listener:
        rules:
            - { path: ^/%api_prefix%,   fallback_format: json }
            - { path: ^/,               fallback_format: html }
