twig:
    default_path: '%kernel.project_dir%/templates'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - bootstrap_4_horizontal_layout.html.twig
        - admin/fields.html.twig
