language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_script:
    - ls -la
    - rm -rf composer.lock
    - composer install

script:
    - php bin/phpunit --debug

notifications:
    email: false
