admin:
    resource: ../../src/Controller/Admin
    prefix: /%admin_prefix%
    type: annotation

controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
