parameters:
    locale: zh_CN
    admin_prefix: admin
    api_prefix: api

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $publicDir: '%kernel.project_dir%/public'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Menu\Builder:
        tags: [{ name: knp_menu.menu_builder, method: createMainMenu, alias: main }]

    App\Form\AttributeType\TextAttributeType:
        tags: [{ name: app.attribute_type, alias: text }]

    App\Form\AttributeType\TextareaAttributeType:
        tags: [{ name: app.attribute_type, alias: textarea }]

    App\Form\AttributeType\RadioAttributeType:
        tags: [{ name: app.attribute_type, alias: radio }]

    App\Form\AttributeType\CheckboxAttributeType:
        tags: [{ name: app.attribute_type, alias: checkbox }]

    App\Form\AttributeType\SelectAttributeType:
        tags: [{ name: app.attribute_type, alias: select }]
